export const buttonVariant = {
  primary: 'text-indigo-600 bg-indigo-200 border-indigo-400',
  secondary: 'text-gray-800 bg-gray-300 border-gray-400',
  success: 'text-green-800 bg-green-200 border-green-400',
  danger: 'text-red-800 bg-red-200 border-red-400',
  warning: 'text-yellow-800 bg-yellow-200 border-yellow-400',
  info: 'text-blue-800 bg-blue-200 border-blue-400',
  light: 'text-gray-600 bg-gray-100 border-gray-200',
  dark: 'text-gray-800 bg-gray-500 border-gray-800',
  'primary-outline': 'text-indigo-600 bg-white border-indigo-600',
  'secondary-outline': 'text-gray-600 bg-white border-gray-600',
  'success-outline': 'text-green-600 bg-white border-green-600',
  'danger-outline': 'text-red-400 bg-white border-red-400',
  'warning-outline': 'text-yellow-600 bg-white border-yellow-600',
  'info-outline': 'text-blue-600 bg-white border-blue-600',
  'light-outline': 'text-gray-600 bg-white border-gray-600',
  'dark-outline': 'text-gray-800 bg-white border-gray-800',
  'primary-solid': 'text-white bg-indigo-600 border-indigo-600',
  'secondary-solid': 'text-white bg-gray-600 border-gray-600',
  'success-solid': 'text-white bg-green-600 border-green-600',
  'danger-solid': 'text-white bg-red-400 border-red-400',
  'warning-solid': 'text-white bg-yellow-600 border-yellow-600',
  'info-solid': 'text-white bg-blue-600 border-blue-600',
  'light-solid': 'text-white bg-gray-600 border-gray-600',
  'dark-solid': 'text-white bg-gray-800 border-gray-800'
};

export const hoverButtonVariant = {
  primary: 'hover:bg-indigo-300',
  secondary: 'hover:bg-gray-400',
  success: 'hover:bg-green-300',
  danger: 'hover:bg-red-300',
  warning: 'hover:bg-yellow-300',
  info: 'hover:bg-blue-300',
  light: 'hover:bg-gray-200',
  dark: 'hover:bg-gray-600',
  'primary-outline': 'hover:bg-indigo-600 hover:text-white',
  'secondary-outline': 'hover:bg-gray-600 hover:text-white',
  'success-outline': 'hover:bg-green-600 hover:text-white',
  'danger-outline': 'hover:bg-red-600 hover:text-white',
  'warning-outline': 'hover:bg-yellow-600 hover:text-white',
  'info-outline': 'hover:bg-blue-600 hover:text-white',
  'light-outline': 'hover:bg-gray-600 hover:text-white',
  'dark-outline': 'hover:bg-gray-800 hover:text-white',
  'primary-solid': 'hover:bg-indigo-700 hover:border-indigo-700',
  'secondary-solid': 'hover:bg-gray-700 hover:border-gray-700',
  'success-solid': 'hover:bg-green-700 hover:border-green-700',
  'danger-solid': 'hover:bg-red-700 hover:border-red-700',
  'warning-solid': 'hover:bg-yellow-700 hover:border-yellow-700',
  'info-solid': 'hover:bg-blue-700 hover:border-blue-700',
  'light-solid': 'hover:bg-gray-700 hover:border-gray-700',
  'dark-solid': 'hover:bg-gray-900 hover:border-gray-900'
};

export const buttonSize = {
  xs: 'text-xs',
  sm: 'text-sm',
  nl: 'text-base',
  lg: 'text-lg'
};
